name: LaTeX Build

on:
  push: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX document
      uses: dante-ev/latex-action@latest
      with:
        root_file: main.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: main.pdf
        path: main.pdf
