name: LaTeX Build with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive

    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX document
      run: |
        pdflatex main.tex
        bibtex main
        pdflatex main.tex
        pdflatex main.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: main.pdf
        path: main.pdf