name: LaTeX Build with Docker

on:
  push: # Run on pushes ...
    branches: # ... to the following branches
      - main
      - exercise-5
  pull_request: # ... and on PR activity ...
    types: # ... of the following types... 
      - synchronize # Run on PR syncs (pushes to branches with open PRs). More on types: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request

permissions:
  pull-requests: write 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive

    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX document
      run: |
        pdflatex main.tex
        bibtex main
        pdflatex main.tex
        pdflatex main.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: main.pdf
        path: main.pdf
  
  comment:
      needs: build
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Environment variables can be set like this
      
      steps:
      - uses: actions/checkout@v4
        # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@master
        id: findPr # Use this ID to refer to the step later
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: main.pdf
          path: main.pdf
          
      - name: Get the artifact URL
        id: get-url # Use this ID to refer to the step later
        run: echo "url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts" >> $GITHUB_ENV # Add the output to the environment

      - name: Comment on the pull request
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ env.GITHUB_TOKEN }} # Retrieve environment variables with the ${{ env.VARIABLE_NAME }} syntax
          issue-number: ${{ steps.findPr.outputs.pr }} # Use the output from the `findPr` step
          body: "The recent output can be accessed [here](${{ env.url }}) or directly download the [main.pdf](./main.pdf)." # Use the output from the `get-url` step
