name: LaTeX Build with Docker

on:
  push:
    branches:
      - main
      - exercise-5
  pull_request:

permissions:
  pull-requests: write 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive

    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX document
      run: |
        pdflatex main.tex
        bibtex main
        pdflatex main.tex
        pdflatex main.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: main.pdf
        path: main.pdf
  
    comment:
      needs: build
      runs-on: ubuntu-latest
      
      steps:
      - name: Get the artifact URL
        id: get-url
        run: echo "Artifact URL: ${{ github.event.pull_request.html_url }}/artifacts/main.pdf"
      
      - name: Comment on the pull request
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: "The compiled PDF is available here."
