name: LaTeX Build with Docker

on:
  push:
    branches:
      - main
      - exercise-5
  pull_request:

permissions:
  pull-requests: write 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive

    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX document
      run: |
        pdflatex main.tex
        bibtex main
        pdflatex main.tex
        pdflatex main.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: main.pdf
        path: main.pdf

  comment:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Download PDF artifact
          uses: actions/download-artifact@v4
          with:
            name: main.pdf
            path: ./artifact
        
        - name: Comment on PR
          uses: actions/github-script@v6
          with:
            script: |
              const fs = require('fs');
              const artifactUrl = `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts`;
              const comment = `The PDF has been generated. You can download it [here](${artifactUrl}).`;
              const issue_number = context.payload.pull_request.number;

              await github.rest.issues.createComment({
                ...context.repo,
                issue_number,
                body: comment
              });
