name: LaTeX Build with Docker

on:
  push:
    branches:
      - main
      - exercise-5
  pull_request:
    types: [synchronize]

permissions:
  pull-requests: write 

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive

    steps:
    - uses: actions/checkout@v4
    - name: Compile LaTeX document
      run: |
        pdflatex main.tex
        bibtex main
        pdflatex main.tex
        pdflatex main.tex
    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: main.pdf
        path: main.pdf
  
  comment:
      needs: build
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
      
      steps:
      - uses: actions/checkout@v4
        # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@master
        id: findPr
        with:
          # Can be "open", "closed", or "all".  Defaults to "open".
          state: open

      - name: Get the artifact URL
        id: get-url
        run: echo "url=${{ github.event.pull_request.html_url }}/artifacts/main.pdf" >> $GITHUB_ENV

      - name: Comment on the pull request
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          issue-number: ${{ steps.findPr.outputs.pr }}
          body: "The compiled PDF is available here: ${{ steps.get-url.outputs.url }}"
